import Head from 'next/head'
import Image from 'next/image'
import { Inter, Poppins } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar'
import HeroSection from '@/components/heroSection'
import Features from '@/components/features'
import DataSection from '@/components/dataSection'
import CardSection from '@/components/cardSection'
import { Box } from '@chakra-ui/react'
import BlueSection from '@/components/blueSection'
import ReadySection from '@/components/readySection'
import FooterSection from '@/components/footerSection'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box bg="#000000">
          <div><Navbar /></div>
          <div><HeroSection /></div>
          <div><Features /></div>
          <div><DataSection /></div>
          <div><CardSection /></div>
          <div><BlueSection /></div>
          <div><ReadySection /></div>
          <div><FooterSection /></div>
        </Box>
      </main>

    </>
  )
}
